#!/usr/bin/env bash
#
# update-homebrew.sh - Update Homebrew formula for Skillrunner
#
# This script manually updates the Homebrew formula for local testing or manual releases.
# For automated releases, the GitHub Actions workflow handles this automatically.
#
# Usage:
#   ./scripts/update-homebrew.sh <version> [--push]
#
# Arguments:
#   version    Version tag (e.g., v0.1.0 or 0.1.0)
#   --push     Optional: Push changes to homebrew-skillrunner repo
#
# Examples:
#   ./scripts/update-homebrew.sh v0.1.0           # Generate formula locally
#   ./scripts/update-homebrew.sh v0.1.0 --push    # Generate and push to tap repo
#
# Requirements:
#   - curl
#   - git (if --push is used)
#   - HOMEBREW_TAP_GITHUB_TOKEN environment variable (if --push is used)
#

set -euo pipefail

# Configuration
REPO_OWNER="jbctechsolutions"
REPO_NAME="skillrunner"
TAP_REPO="homebrew-skillrunner"
FORMULA_DIR="Formula"
FORMULA_NAME="skillrunner.rb"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Print usage information
usage() {
    cat << EOF
Usage: $(basename "$0") <version> [--push]

Update Homebrew formula for Skillrunner

Arguments:
  version    Version tag (e.g., v0.1.0 or 0.1.0)
  --push     Optional: Push changes to homebrew-skillrunner repo

Examples:
  $(basename "$0") v0.1.0           # Generate formula locally
  $(basename "$0") v0.1.0 --push    # Generate and push to tap repo

Environment Variables:
  HOMEBREW_TAP_GITHUB_TOKEN    GitHub token with write access to tap repo (required for --push)

EOF
    exit 1
}

# Validate version format
validate_version() {
    local version="$1"
    # Remove 'v' prefix if present
    version="${version#v}"

    # Check if version matches semantic versioning pattern
    if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
        log_error "Invalid version format: $version"
        log_error "Expected format: X.Y.Z or X.Y.Z-suffix (e.g., 0.1.0 or 0.1.0-beta)"
        exit 1
    fi

    echo "$version"
}

# Download checksums file from GitHub release
download_checksums() {
    local version="$1"
    local checksums_url="https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download/v${version}/checksums.txt"
    local checksums_file
    checksums_file=$(mktemp)

    log_info "Downloading checksums from: $checksums_url"

    if ! curl -sL --fail -o "$checksums_file" "$checksums_url"; then
        log_error "Failed to download checksums.txt"
        log_error "Make sure release v${version} exists and has checksums.txt"
        rm -f "$checksums_file"
        exit 1
    fi

    echo "$checksums_file"
}

# Extract SHA256 for a specific platform/arch
get_sha256() {
    local checksums_file="$1"
    local os="$2"
    local arch="$3"
    local pattern="${os}_${arch}"

    local sha256
    sha256=$(grep "$pattern" "$checksums_file" | awk '{print $1}')

    if [[ -z "$sha256" ]]; then
        log_error "Could not find checksum for ${os}_${arch}"
        exit 1
    fi

    echo "$sha256"
}

# Generate the Homebrew formula
generate_formula() {
    local version="$1"
    local darwin_arm64_sha="$2"
    local darwin_amd64_sha="$3"
    local linux_arm64_sha="$4"
    local linux_amd64_sha="$5"
    local output_file="$6"

    log_info "Generating Homebrew formula..."

    cat > "$output_file" << EOF
# typed: false
# frozen_string_literal: true

# Homebrew formula for Skillrunner
# Local-first AI workflow orchestration tool
#
# Installation:
#   brew tap ${REPO_OWNER}/${TAP_REPO#homebrew-}
#   brew install skillrunner
#
# Or directly:
#   brew install ${REPO_OWNER}/${TAP_REPO#homebrew-}/skillrunner
#
# Generated by: scripts/update-homebrew.sh
# Version: ${version}

class Skillrunner < Formula
  desc "Local-first AI workflow orchestration tool"
  homepage "https://github.com/${REPO_OWNER}/${REPO_NAME}"
  version "${version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download/v${version}/skillrunner_${version}_darwin_arm64.tar.gz"
      sha256 "${darwin_arm64_sha}"
    else
      url "https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download/v${version}/skillrunner_${version}_darwin_amd64.tar.gz"
      sha256 "${darwin_amd64_sha}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download/v${version}/skillrunner_${version}_linux_arm64.tar.gz"
      sha256 "${linux_arm64_sha}"
    else
      url "https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download/v${version}/skillrunner_${version}_linux_amd64.tar.gz"
      sha256 "${linux_amd64_sha}"
    end
  end

  def install
    bin.install "sr"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sr version")
  end
end
EOF

    log_success "Formula generated: $output_file"
}

# Push formula to homebrew tap repository
push_to_tap() {
    local version="$1"
    local formula_file="$2"

    if [[ -z "${HOMEBREW_TAP_GITHUB_TOKEN:-}" ]]; then
        log_error "HOMEBREW_TAP_GITHUB_TOKEN environment variable is required for --push"
        exit 1
    fi

    local tap_dir
    tap_dir=$(mktemp -d)

    log_info "Cloning homebrew tap repository..."
    if ! git clone "https://x-access-token:${HOMEBREW_TAP_GITHUB_TOKEN}@github.com/${REPO_OWNER}/${TAP_REPO}.git" "$tap_dir" 2>/dev/null; then
        log_error "Failed to clone tap repository"
        log_error "Check that HOMEBREW_TAP_GITHUB_TOKEN has write access to ${REPO_OWNER}/${TAP_REPO}"
        rm -rf "$tap_dir"
        exit 1
    fi

    log_info "Updating formula in tap repository..."
    mkdir -p "${tap_dir}/${FORMULA_DIR}"
    cp "$formula_file" "${tap_dir}/${FORMULA_DIR}/${FORMULA_NAME}"

    cd "$tap_dir"
    git config user.name "skillrunner-bot"
    git config user.email "bot@skillrunner.dev"

    if git diff --quiet; then
        log_warning "No changes to commit - formula is already up to date"
        rm -rf "$tap_dir"
        return 0
    fi

    git add "${FORMULA_DIR}/${FORMULA_NAME}"
    git commit -m "Update skillrunner to v${version}"

    log_info "Pushing changes to tap repository..."
    if ! git push origin main; then
        log_error "Failed to push to tap repository"
        rm -rf "$tap_dir"
        exit 1
    fi

    rm -rf "$tap_dir"
    log_success "Formula pushed to ${REPO_OWNER}/${TAP_REPO}"
}

# Main function
main() {
    # Parse arguments
    if [[ $# -lt 1 ]]; then
        usage
    fi

    local version_arg="$1"
    local push_flag=false

    shift
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --push)
                push_flag=true
                shift
                ;;
            -h|--help)
                usage
                ;;
            *)
                log_error "Unknown argument: $1"
                usage
                ;;
        esac
    done

    # Validate and normalize version
    local version
    version=$(validate_version "$version_arg")
    log_info "Updating formula for version: ${version}"

    # Download checksums
    local checksums_file
    checksums_file=$(download_checksums "$version")

    log_info "Checksums downloaded:"
    cat "$checksums_file"
    echo ""

    # Extract SHA256 for each platform
    local darwin_arm64_sha darwin_amd64_sha linux_arm64_sha linux_amd64_sha
    darwin_arm64_sha=$(get_sha256 "$checksums_file" "darwin" "arm64")
    darwin_amd64_sha=$(get_sha256 "$checksums_file" "darwin" "amd64")
    linux_arm64_sha=$(get_sha256 "$checksums_file" "linux" "arm64")
    linux_amd64_sha=$(get_sha256 "$checksums_file" "linux" "amd64")

    log_info "SHA256 checksums:"
    echo "  darwin_arm64: ${darwin_arm64_sha}"
    echo "  darwin_amd64: ${darwin_amd64_sha}"
    echo "  linux_arm64:  ${linux_arm64_sha}"
    echo "  linux_amd64:  ${linux_amd64_sha}"
    echo ""

    # Generate formula
    local output_dir="${BASH_SOURCE[0]%/*}/../homebrew"
    mkdir -p "$output_dir"
    local formula_file="${output_dir}/${FORMULA_NAME}"

    generate_formula "$version" "$darwin_arm64_sha" "$darwin_amd64_sha" "$linux_arm64_sha" "$linux_amd64_sha" "$formula_file"

    # Show generated formula
    echo ""
    log_info "Generated formula contents:"
    echo "---"
    cat "$formula_file"
    echo "---"
    echo ""

    # Push if requested
    if $push_flag; then
        push_to_tap "$version" "$formula_file"
    else
        log_info "Formula saved to: $formula_file"
        log_info "Run with --push to push to the homebrew tap repository"
    fi

    # Cleanup
    rm -f "$checksums_file"

    log_success "Done!"
}

# Run main function
main "$@"
